# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery657', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['pk']},
        ),
    ]
