# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery657.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery657', '0006_auto_20171029_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art', to='gallery657.Collection'),
        ),
        migrations.AlterField(
            model_name='art',
            name='thumb_nail',
            field=models.FileField(blank=True, null=True, upload_to=b'gallery657', validators=[gallery657.models.validate_file_type]),
        ),
    ]
