# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('gallery657', '0009_auto_20190316_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
