# Generated by Django 3.2.6 on 2021-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery657', '0013_auto_20190824_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
