# Generated by Django 3.2.6 on 2021-08-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery657', '0014_auto_20210821_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
